version: '3'

services:
  gon-pypy:
    build:
      context: .
      args:
        - IMAGE_NAME=${PYPY_IMAGE_NAME}
        - IMAGE_VERSION=${PYPY_IMAGE_VERSION}
    image: lycantropos/gon-pypy:6.0.0-alpha
    volumes:
      - ./gon:/opt/gon/gon
      - ./pyproject.toml:/opt/gon/pyproject.toml
      - ./README.md:/opt/gon/README.md
      - ./setup.py:/opt/gon/setup.py
      - ./tests:/opt/gon/tests
    entrypoint: pytest
