version: '3'

services:
  gon-pypy:
    build:
      context: .
      args:
        - IMAGE_NAME=${PYPY_IMAGE_NAME}
        - IMAGE_VERSION=${PYPY_IMAGE_VERSION}
    image: lycantropos/gon-pypy:4.1.0
    volumes:
      - ./gon:/opt/gon/gon
      - ./pytest.ini:/opt/gon/pytest.ini
      - ./README.md:/opt/gon/README.md
      - ./requirements-tests.txt:/opt/gon/requirements-tests.txt
      - ./requirements.txt:/opt/gon/requirements.txt
      - ./setup.py:/opt/gon/setup.py
      - ./tests:/opt/gon/tests
    entrypoint: pytest
