version: '3'

services:
  gon-cpython:
    build:
      context: .
      args:
        - IMAGE_NAME=${CPYTHON_IMAGE_NAME}
        - IMAGE_VERSION=${CPYTHON_IMAGE_VERSION}
    image: lycantropos/gon-cpython:5.0.0
    volumes:
      - ./gon:/opt/gon/gon
      - ./pyproject.toml:/opt/gon/pyproject.toml
      - ./README.md:/opt/gon/README.md
      - ./setup.py:/opt/gon/setup.py
      - ./tests:/opt/gon/tests
    entrypoint: pytest
