version: '3'

services:
  gon-pypy:
    build:
      context: .
      args:
      - PYTHON_IMAGE=${PYPY_IMAGE_NAME}
      - PYTHON_IMAGE_VERSION=${PYPY_IMAGE_VERSION}
    image: lycantropos/gon-pypy:3.1.0
    volumes:
      - ./gon/:/opt/gon/gon/
      - ./tests/:/opt/gon/tests/
      - ./README.md:/opt/gon/README.md
      - ./requirements.txt:/opt/gon/requirements.txt
      - ./requirements-tests.txt:/opt/gon/requirements-tests.txt
      - ./setup.py:/opt/gon/setup.py
      - ./pytest.ini:/opt/gon/pytest.ini
    entrypoint: pytest
