name: CI

on:
  push:
    branches:
      - 'master'
      - '[0-9].[0-9]+'  # matches to backport branches, e.g. 3.6
    tags: [ 'v*' ]
  pull_request:
    branches:
      - 'master'
      - '[0-9].[0-9]+'
  schedule:
    - cron:  '0 6 * * *'  # Daily 6AM UTC build

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    strategy:
      matrix:
        pyver: ['pypy3', '3.5', '3.6', '3.7', '3.8', '3.9', '3.10']
        os: ['ubuntu', 'macos', 'windows']
      fail-fast: true
    runs-on: ${{ matrix.os }}-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: 'Setup Python ${{ matrix.pyver }}'
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.pyver }}
    - name: 'Install packaging tools'
      run: python -m pip install -U pip wheel setuptools build twine
    - name: 'Install coverage dependencies'
      run: python -m pip install --upgrade coverage codecov
    - name: 'Install dependencies'
      run: python -m pip install -r requirements.txt
    - name: 'Run doctests'
      run: coverage run -m doctest README.md
    - name: 'Install tests dependencies'
      run: python -m pip install -r requirements-tests.txt
    - name: 'Run tests'
      run: coverage run --append -m pytest
    - name: 'Collect coverage'
      run: coverage xml
    - name: Upload coverage
      uses: codecov/codecov-action@v2.1.0
